# Generated by Django 5.2.8 on 2025-11-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('subject', models.CharField(choices=[('AGN', 'Agronegócio'), ('GTE', 'Gestão Empresarial'), ('SST', 'Saúde e Segurança do Trabalho'), ('TRN', 'Treinamentos'), ('OTR', 'Outro')], default='OTR', verbose_name='Assunto')),
                ('text', models.TextField(max_length=1000, verbose_name='Mensagem')),
                ('replied', models.BooleanField(default=False, verbose_name='Respondida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-created_at'],
            },
        ),
    ]
