# Generated by Django 5.2.8 on 2025-11-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('content', models.TextField(max_length=2550, verbose_name='Conteúdo')),
                ('sent', models.BooleanField(default=False, verbose_name='Enviado')),
                ('scheduled_date', models.DateField(verbose_name='Data agendada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conteúdo da NewsLetter',
                'verbose_name_plural': 'Conteúdos da NewsLetter',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
