# Generated by Django 5.2.8 on 2025-11-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettermessage',
            name='content',
            field=models.TextField(max_length=10000, verbose_name='Conteúdo'),
        ),
    ]
