# Generated by Django 5.2.8 on 2025-11-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Prefiro não especificar')], default='N', max_length=1, verbose_name='Gênero')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('professional_area', models.CharField(choices=[('AG', 'Agrônomo'), ('PR', 'Produtor Rural'), ('GE', 'Gestor(a) Empresarial'), ('SS', 'Profissional de SST'), ('ES', 'Estudante'), ('CO', 'Consultor(a)'), ('PE', 'Pesquisador(a)'), ('OU', 'Outro')], default='OU', max_length=2, verbose_name='Área profissional')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de inscrição')),
            ],
            options={
                'verbose_name': 'Assinante',
                'verbose_name_plural': 'Assinantes',
                'ordering': ['first_name'],
            },
        ),
    ]
